### ISSUE TITLE
v1.0.1 - daily and monthly stats CSVs contain a doubled-up csv extension

### ISSUE THREAD

**Issue by barrettnet** [fontora/offline_usage_metrics#2]
Lines 159 and 175 of offline_usage_metrics/default/data/ui/views/oum_statistics.xml are used to download the CSVs.   I suspect that the .csv should be removed from the specified filenames as it looks like setting the outputMode to csv causes an additional .csv to be appended to the filename.

And "splunk" is misspelt as "slunk" in the filename in line 175 of the same file.

**Comment by fontora** [comment]
Updated, 1.0.3 available!

**Comment by fontora** [comment]
.
